# Generated by Django 5.0.1 on 2024-01-14 04:56

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=180, null=True, unique=True)),
                ('contact_number', models.IntegerField(unique=True)),
                ('qualification', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specility', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('specilist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctorspecility')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('contact_number', models.IntegerField()),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('blood_group', models.CharField(choices=[('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-')], max_length=10)),
                ('Appointment_time', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Presciption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.FileField(blank=True, null=True, upload_to='prescription')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.patient')),
            ],
        ),
    ]
